export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_BUDGETS_START = "FETCH_BUDGETS_START";
export const FETCH_BUDGETS_SUCCESS = "FETCH_BUDGETS_SUCCESS";
export const FETCH_BUDGETS_FAIL = "FETCH_BUDGETS_FAIL";

export const SINGLE_BUDGET = "SINGLE_BUDGET";
